---
name: release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: telia-actions/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: v
