name: Check Repo Visibility

on:
  push:

jobs:
  check-repo-visibility:
    runs-on: ubuntu-latest
    steps:
      - name: Check for public repo visibility
        run: |
          find . -name '*.yml' -type f -print0 | xargs -0 grep -H 'repoVisibility: "public"' || true
          if grep -r -q 'repoVisibility: "public"' .; then
            echo "Public repo visibility is not allowed"
            exit 1
          fi
